apiVersion: v1
kind: Service
metadata:
  name: varasiddha-app-service
spec:
  type: LoadBalancer
  selector:
    app: varasiddha-app
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
